#!/bin/bash


tar xf linux-3.2.6.tar.xz 
cd linux-3.2.6
make mrproper
make LANG=en_US.UTF-8 LC_ALL= menuconfig
make
make modules_install
cp -v arch/x86_64/boot/bzImage /boot/vmlinuz-3.2.6-lfs-7.1
cp -v System.map /boot/System.map-3.2.6
cp -v .config /boot/config-3.2.6
install -d /usr/share/doc/linux-3.2.6
cp -r Documentation/* /usr/share/doc/linux-3.2.6
cd ..
chown -R 0:0 linux-3.2.6

install -v -m755 -d /etc/modprobe.d

cat > /etc/modprobe.d/usb.conf << "EOF"
install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

EOF

exit
